apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django-app
          image: europe-west1-docker.pkg.dev/nci-research-project/django-repo/django-app:latest
          ports:
            - containerPort: 8000
