apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-rwx
provisioner: kubernetes.io/azure-file
parameters:
  skuName: Standard_LRS
  storageAccount: ncifilestorage
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
  - actimeo=30

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-media-pvc-rwx
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-rwx
  resources:
    requests:
      storage: 5Gi
