apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-rwx
provisioner: file.csi.azure.com
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
parameters:
  skuName: Standard_LRS