apiVersion: batch/v1
kind: Job
metadata:
  name: create-superuser
spec:
  template:
    spec:
      containers:
        - name: create-superuser
          image: nciregistryacr.azurecr.io/django-app:commit-ba81a36f762d42218f51ad18d642f1a2da2cd7ef
          command: ["python", "manage.py", "createsuperuser", "--noinput"]
          env:
            - name: DJANGO_SUPERUSER_USERNAME
              value: "sahilx0729"
            - name: DJANGO_SUPERUSER_EMAIL
              value: "sahil.shaikh048@hotmail.com"
            - name: DJANGO_SUPERUSER_PASSWORD
              value: "S@hil029"
            - name: DEBUG
              value: "True"
            - name: SECRET_KEY
              value: "dummy"
            - name: DB_NAME
              value: "Research_Project"
            - name: DB_USER
              value: "django_user"
            - name: DB_PASSWORD
              value: "django_pass"
            - name: DB_HOST
              value: "db"
            - name: DB_PORT
              value: "5432"
      restartPolicy: Never
  backoffLimit: 3
