apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  labels:
    app: django-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django-container
          image: europe-west1-docker.pkg.dev/nci-research-project/django-repo/django-app:latest
          ports:
            - containerPort: 8000
          env:
            - name: DEBUG
              value: "True"
            - name: SECRET_KEY
              value: "bun6+_ovp679c-z=h6bh1=tj%z3suy1eg(xs^#jkj(z0y8)^0u"
            - name: DB_NAME
              value: "Research_Project"
            - name: DB_USER
              value: "django_user"
            - name: DB_PASSWORD
              value: "django_pass"
            - name: DB_HOST
              value: "db"
            - name: DB_PORT
              value: "5432"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
