apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  labels:
    app: django-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django-container
          image: PLACEHOLDER_IMAGE  # This gets replaced dynamically in GitHub Actions
          ports:
            - containerPort: 8000
          env:
            - name: DEBUG
              value: "True"
            - name: SECRET_KEY
              value: "bun6+_ovp679c-z=h6bh1=tj%z3suy1eg(xs^#jkj(z0y8)^0u"
            - name: DB_NAME
              value: "Research_Project"
            - name: DB_USER
              value: "django_user"
            - name: DB_PASSWORD
              value: "django_pass"
            - name: DB_HOST
              value: "db"
            - name: DB_PORT
              value: "5432"
          volumeMounts:
            - name: media-storage
              mountPath: /app/media

          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 40
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10

          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"

      volumes:
        - name: media-storage
          persistentVolumeClaim:
            claimName: {{PVC_NAME}}  # Injected dynamically in CI/CD
