apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: aws-efs
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-036c00aa067a52dec
  directoryPerms: "700"
reclaimPolicy: Delete
volumeBindingMode: Immediate
