apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-media-pvc-rwx
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefile-rwx
