apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-rwx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: managed-premium
