name: Deploy Django to GKE

on:
  push:
    branches:
      - main  # or master if that's your default

env:
  PROJECT_ID: nci-research-project
  GAR_LOCATION: europe-west1
  REPO_NAME: django-repo
  IMAGE_NAME: django-app
  CLUSTER_NAME: nci-research-cluster
  CLUSTER_REGION: europe-west1

jobs:
  deploy:
    name: Build & Deploy to GKE
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          docker build -t $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:$GITHUB_SHA .
          docker push $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:$GITHUB_SHA

      - name: Set up Kubeconfig
        run: |
          gcloud container clusters get-credentials $CLUSTER_NAME --region $CLUSTER_REGION

      - name: Deploy to GKE
        run: |
          kubectl set image deployment/django-app django-container=$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:$GITHUB_SHA
